### ISSUE TITLE
There is no MODEL selection line in [New UI]

### ISSUE THREAD

**Issue by Nyandaro** [ParisNeo/gpt4all-ui#209]
## Current Behavior
There is no MODEL selection line in [New UI]
I feel like it used to be
I feel like I've been gone for some time

## Steps to Reproduce
1. clean install webui.bat
2. add  personalities folder
3. put model in model folder
4. webui.bat start

## Possible Solution
GPT4All\web\src\views\SettingsView.vue
Is this file the problem?

**Comment by Nyandaro** [comment]
I'm sorry I still can't see it, is it just me?

**Comment by okkebal** [comment]
Just click on a model thats downloaded to select it.

**Comment by okkebal** [comment]
Old models that are not in the list can be added by editing. /backends/modelname/models.yaml or you can select it by editing /config/local_default.yaml

You can manually set the model there or you can set use_new_ui to false.

**Comment by Nyandaro** [comment]
Even with that setting, the MODEL is not loaded
I'm on Windows 10, but does it work on Linux or Mac?

**Comment by okkebal** [comment]
If you restart the webui it should pull in the latest changes. Existing models should now be visible in the selection list. Just click the one you want.

**Comment by Nyandaro** [comment]
I was able to confirm that the selected MODEL works
thanks
