### ISSUE TITLE
llama_cpp seems broken

### ISSUE THREAD

**Issue by okkebal** [ParisNeo/gpt4all-ui#215]
I get this on a model that worked just last week. Guess some changes where made:

Backend loaded successfully
Loading model : models\llama_cpp_official\medalpaca-13B.ggmlv2.q4_0.bin
llama.cpp: loading model from ./models/llama_cpp_official/medalpaca-13B.ggmlv2.q4_0.bin
error loading model: llama.cpp: tensor '=/ë╔ëÜívÜCW£;╗h' should not be 1004666880-dimensional
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "Q:\llm\GPT4All\gpt4all_api\api.py", line 190, in _rebuild_model
    self.model = self.backend(self.config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Q:\llm\GPT4All\backends\llama_cpp_official\__init__.py", line 43, in __init__
    self.model = Llama(model_path=f"./models/llama_cpp_official/{self.config['model']}", n_ctx=self.config["ctx_size"], n_gpu_layers=self.config["n_gpu_layers"], seed=seed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Q:\llm\GPT4All\env\Lib\site-packages\llama_cpp\llama.py", line 162, in __init__
    assert self.ctx is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
Couldn't build model

**Comment by ParisNeo** [comment]
Yes, this is linked to the fact that the llamacpp coders can't keep retrocompatibility through their code version.
I am sorry for that, but you need to change the model to a newer version. The Bloke has new models in his hugging face:
https://huggingface.co/TheBloke

**Comment by okkebal** [comment]
I already have these new models. The new stuff after the may 19 code breakage, I all worked yesterday. Did it happen again? Do we need new models again? These new models are not here yet... But I think something is wrong on my end here.

**Comment by okkebal** [comment]
PS: I just did a fresh install on everything. GPT4ALL and c_transformers models seem to work fine

**Comment by okkebal** [comment]
I Fixed it by moving my models to /models/py_llama_cpp and using the py_llama_cpp backend. Now I can run them again...
