### ISSUE TITLE
Windows Error 0xc000001d

### ISSUE THREAD

**Issue by imchung** [ParisNeo/gpt4all-ui#246]
I got the windows error message and the promp shows 'not model has been loaded'

Couldn't build model ggml-nous-gpt4-vicuna-13b.bin : [WinError -1073741795] Windows Error 0xc000001d

Any hint to fix this ?

## Steps to Reproduce
Environment:
 - Macbook Pro, WIndows 11 VM
 - Python: Python 3.10.11

1. execute Webui.Bat
2. download model : ggml-nous-gpt4-vicuna-13b.bin 
3. select the model and save, confirm yalm file 
4. while try to load the model, displays the error message and prompt says that ' model is not loaded' 
5. the content of local_config.yaml
auto_read: false
binding: gpt_4all
config: local_config
ctx_size: 2048
db_path: databases/database.db
debug: false
host: localhost
language: en-US
model: ggml-nous-gpt4-vicuna-13b.bin
n_gpu_layers: 20
n_predict: 1024
n_threads: 8
nb_messages_to_remember: 5
override_personality_model_parameters: false
personality: gpt4all
personality_category: default
personality_language: english
port: 9600
repeat_last_n: 40
repeat_penalty: 1.2
seed: -1
temperature: 0.1
top_k: 50
top_p: 0.95
use_avx2: true
use_gpu: false
use_new_ui: true
user_name: user
version: 5
voice: ''

**Comment by ShikoThePro** [comment]
This error happen to me too??

But no one answer me

**Comment by imchung** [comment]
I found some clue for this error at [https://github.com/nomic-ai/gpt4all/issues/758]
Can i apply this solution for this error? I couldn't find the 'gpt4all-backend' directory.
